Extract application configuration and info/error/success messages into config file
evolvedbinary/prosemirror-lwdita pull request #419
Opened 2024-10-09 18:15 UTC by plutonik-a

This PR will facilitate configuring following features in `./packages/prosemirror-lwdita/app-config.ts`:
* Strings for error page and toasts containing error/success/info messages 
* serverURLs
* GitHub API endpoints (e.g. for easily creating URLs in test suite)
* enabling/disabling CORS
* Petal App User / Email 
* Default text modules for Petal Commit messages

2024-10-14 08:10 UTC, marmoure requested changes
The cors enable trigger should be something like 
```shell
set env=dev
yarn start:backend
```

2024-10-14 08:10 UTC, marmoure commented on packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
> +        name: PETAL_COMMITTER_NAME,
It would be more appropriate if we name it `PetalBot_commiter_name`, we are using PetalBot everywhere now.

2024-10-14 08:10 UTC, marmoure commented on packages/prosemirror-lwdita-backend/src/server.ts
> +import { serverConfig, enableCors } from '@evolvedbinary/prosemirror-lwdita';
I think these values should be passed as environment variables instead.

2024-10-14 08:10 UTC, marmoure commented on packages/prosemirror-lwdita/src/app-config.ts
> +  value: process.env.GITHUB_CLIENT_ID || 'Iv23li0Pvl3E4crXIBQ0',
We should remove the default value, is it's not passed as an environment variable then something is wrong.

2024-10-14 08:10 UTC, marmoure commented on packages/prosemirror-lwdita/src/app-config.ts
> +export const enableCors = process.env.ENABLE_CORS === 'true';
This value only concerns the backend, why are we setting it in the `prosemirror-lwdita` package?

2024-10-15 15:54 UTC, closed without merging

2024-10-15 15:55 UTC, plutonik-a commented
This PR will be contined in PR https://github.com/evolvedbinary/prosemirror-lwdita/pull/438, therefore closed.